######## SITE SETTINGS #########
title: Gavins Intersect Course edits                # The title of your site
description: "Changes to the Intersect content"     # A short description of your site
repourl: "https://github.com/gjcooper/IntCourses"   # The URL of the GitHub repository holding your markdown files
companyurl: "https://intersect.org.au"              # The location to send people when clicking your company logo
sub-brandurl: "https://learn.intersect.org.au"      # The location to send people to when clicking your company sub-brand logo
contactmessage: "We value your feedback:"           # Call to action message in the footer
surveyurl: "https://inter.fyi/learn/survey"         # The URL of a feedback or interest survey
email: gavin@intersect.org.au                       # Your email contact address
baseurl: "/IntCourses"                              # the subpath of this site, e.g. /blog
url: "https://gjcooper.github.io"                   # the base hostname & protocol for this site, e.g. http://example.com

######## BUILD SETTINGS #########
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
highlighter: rouge
remote_theme: IntersectAustralia/intersect-training-theme@v1.2.1

sass:
  sass_dir: _sass

include: ["courses/"]   # Necessary as Jekyll will exclude directories not beginning with underscore

######## COLLECTIONS #########
collections_dir: "courses"
collections:
  WEBDATA201:    # A unique ID for the course. Must match a directory name (without the `_` prefix)
    output: true  # Tell Jekyll to render files in the collection
    title: "WEBDATA201"    # The actual name for the course
    description: "Refreshed WEBDATA201 course contnt"   # A short description of your site
    relative_url: "/webdata201"    # The subpath of the the site, e.g. /course-001
    permalink: /webdata201/:path   # Will render links in format '<course-url>/<document-path>/<base-filename>'
    licence: "All content on this site is copyright (c) of Libray Carpentries 2021. All rights reserved"   # A statement of the licencing conditions of your site
